---
- hosts: web
  tasks:
   - package:
      name: "httpd"
      state: present
   - copy:
      src: "/local/index.html"
      dest: "/webcontent"
   - file: 
      state: directory
      path: "/webcontent"
   - copy:
      src: "/local/index.html"
      dest: "/webcontent"
   - service: 
      name: "httpd"
      state: restarted
