---
- hosts: storageserver
  tasks:

        - package:
                         name: "scsi-target-utils.x86_64"
                         state: present

        - file:
                         state: directory
                         path: "/gbs"

        - fetch:
                         src: "/etc/tgt/targets.conf"
                         dest: "/gbs/"
                         flat: yes

        - lvol:
                         vg: "blockstorage"
                         lv: "cloudhat"
                         size: "500"
                          
- hosts: webserver
  tasks:
        - file:
                         path: "/gbs/targets.conf"
                         owner: "apache"

        - blockinfile:
                         path: "/gbs/targets.conf"
                         block:  |
                           <target cloudhat>
                               backing-store /dev/blockstorage/cloudhat
                           </target>

- hosts: storageserver
  tasks:
        - copy:
                         src: "/gbs/targets.conf"
                         dest: "/etc/tgt/targets.conf"



        - service:
                         name: "tgtd"
                         state: restarted

- hosts: clientserver
  tasks:
        - open_iscsi:
                         show_nodes: yes
                         discover: yes
                         portal: 192.168.43.46
                         login: yes
                         target: cloudhat
